# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Danielle Honigstein
email: use-contact-page@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Programmer, PhD in Applied Physics. Here are cool things I did with code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielle-honig.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: danielle-h

# Build settings
gem "github-pages", group: :jekyll_plugins
remote_theme: "mmistakes/so-simple-theme@3.2.0"

markdown: kramdown

excerpt_separator: <!--more-->

logo: "/assets/images/dh-diamond.png"
skin: "/assets/css/skins/custom.css"

read_time: true
words_per_minute: 200

paginate: 5
paginate_path: /page:num/

date_format: "%Y-%m-%d"

collections:
  sketches:
    output: true
    permalink: /:collection/:name/

disqus:
  shortname: "danielle-honig"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

search_full_content: true
google-site-verification: "2IV4mZQXYmms3Se9c9rvhR_bCDPBZBeTQTbW46yLdPo"

google_analytics: G-XE6GY7G848

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Footer Links
footer_links:
  - title: Gitlab
    url: https://gitlab.com/dsavir
    icon: fab fa-gitlab
  - title: LinkedIn
    url: https://www.linkedin.com/in/danielle-honigstein-a502bb27/
    icon: fab fa-linkedin
  - title: Medium
    url: https://dsavir-h.medium.com/
    icon: fab fa-medium

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
